# Site
name: "rendrapwk"
title: "Rendra Pratama"
description: "Hayu Urang Miboga Purwakarta"
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: ""
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  rendrapwk:
    name: rendrapwk
    display_name: Rendra Pratama
    # avatar: 'assets/images/avatar.png'
    gravatar: 6df4e4a08725f9fd7743ff537150874394bfbb24e2e36ac7d6d5eaa503090770
    email: rendrapwk@gmail.com
    web: https://rendrapwk.github.io
    description: "KISS - Keep It Simple Sajalah"
  
  admin:
    name: admin
    display_name: admin-pwk
    avatar: 'assets/images/avatar.png'
    #email: admin-rendrapwk@gmail.com
    #web: https://rendrapwk.github.io
    #description: "KISS - Keep It Simple Sajalah"
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
